flowchart LR
    A[VTK.js] --> B[trame-rca]
    B --> C[vtkRemoteInteractionAdapter]

    Da[vtkRenderWindowInteractor] -> Db[vtkInteractorStyle]

    E[Qt] ---> F[QVTKInteractorAdapter]
    
    G[vtkRenderWindowInteractor]
    C -- vtkCommand --> G
    F -- vtkCommand --> G

    G <-. Observer .-> H["MyInteractor (custom)"]
    G <-. Observer.-> I[vtkMRMLWidgets]
