gitGraph
    commit id: " " tag: "9.6.2"
    branch fix-gestures
    commit id: "fix: gestures handling"
    checkout main
    commit id: "....."
    commit id: "..... "
    commit id: "..... "
    merge fix-gestures
    commit tag: "9.7.20260627" id:"  "
    commit id: ".....  "
    commit id: ".....   "
    commit id: ".....   "
    commit id: "   " tag: "9.7.0rc3"
