sequenceDiagram
    participant User
    participant Widget as vtkMRMLCameraWidget /<br/>vtkMRMLSliceIntersectionWidget
    participant IntNode as vtkMRMLInteractionNode
    participant AppLogic as vtkMRMLApplicationLogic
    participant SHLogic as qSlicerSubjectHierarchyPluginLogic
    participant SHPlugins as qSlicerSubjectHierarchyPlugins
    participant Menu as QMenu
    User ->> Widget: Right-Click in View
    Widget ->> Widget: ProcessWidgetMenu()
    Note over Widget: Create vtkMRMLInteractionEventData<br/>Set Type to ShowViewContextMenuEvent
    Widget ->> IntNode: ShowViewContextMenu(eventData)
    IntNode ->> IntNode: InvokeEvent(ShowViewContextMenuEvent, eventData)
    IntNode -->> AppLogic: Observed Event
    AppLogic ->> AppLogic: InvokeEvent(ShowViewContextMenuEvent, eventData)
    AppLogic -->> SHLogic: Observed Event (onDisplayMenuEvent)
    SHLogic ->> SHLogic: onDisplayMenuEvent(nullptr, eventData)
    Note over SHLogic: Identify Scene ItemID

    loop For each Plugin
        SHLogic ->> SHPlugins: showViewContextMenuActionsForItem(sceneItemID, eventDataMap)
        SHPlugins -->> SHLogic: Populate actions (e.g., "Create folder", "Paste")
    end

    SHLogic ->> Menu: exec(QCursor::pos())
    Menu -->> User: Display Context Menu