title: "Develop scientific and medical visualization applications with trame, a stateful web Python framework"
student: "Ulysse DURAND\\\\ENS Lyon  Centrale Lyon"
tutor: "Julien FINET, Director Software Solutions"
UE: "Final Internship Report (TFE)"
subject: "Kitware Europe, Villeurbanne, France"