PR:
  - url: https://github.com/Kitware/trame/pull/867
    description: "docs(tutorial): fix typos and improve clarity"
    status: done
  - url: https://github.com/Kitware/trame/pull/870
    description: "docs(tutorial): upgrade python version from 3.9 to 3.12"
    status: done
  - url: https://github.com/Kitware/trame-vtk/pull/108
    description: "pre-commit update and picture added"
    status: done
  - url: https://github.com/Kitware/trame-vtk/pull/119
    description: "correct github action semantic release build"
    status: done
  - url: https://github.com/Kitware/trame/pull/899
    description: "docs(widgets): widgets list automatically populated"
    status: done
  - url: https://github.com/Kitware/trame/pull/901
    description: "docs(catalog): fix URL after change of repo name"
    status: done
  - url: https://github.com/Kitware/trame/pull/902
    description: "docs(catalogs): change non-kitware repos emoji"
    status: done
  - url: https://github.com/Kitware/trame/pull/903
    description: "docs(catalogs): fix missing apps and add logging"
    status: done
  - url: https://github.com/Kitware/trame/pull/905
    description: ""
    status: done
  - url: https://github.com/Kitware/trame/pull/876
    description: "Fix examples"
    status: done
  - url: https://github.com/Kitware/trame/pull/879
    description: "Fix doc build error after fix-examples"
    status: done
  - url: https://github.com/Kitware/trame/pull/882
    description: "Fix paraview with docker example"
    status: done
  - url: https://github.com/Kitware/trame/pull/883
    description: "Fix paraview with docker example (v2)"
    status: done
  - url: https://github.com/Kitware/trame-tutorial/pull/7
    description: "Upgrade from Vue2 to Vue3 and use TrameApp"
    status: done
  - url: https://github.com/Kitware/trame-tutorial/pull/8
    description: "Finish making all the examples use best practice"
    status: done
  - url: https://github.com/Kitware/trame-tutorial/pull/9
    description: "Finish making all the examples use best practices (v2)"
    status: done
  - url: https://github.com/Kitware/trame/pull/877
    description: "Tutorial corrections, upgrade from Vue2 to Vue3 and use TrameApp"
    status: done
  - url: https://github.com/Kitware/trame-cookiecutter/pull/26
    description: "fix ruff errors"
    status: done
  - url: https://github.com/Kitware/trame-cookiecutter/pull/27
    description: "fix(pre-commit): fix component application creation error"
    status: done
  - url: https://github.com/Kitware/trame-cookiecutter/pull/28
    description: "Put project version in the served umd.js file url"
    status: done
  - url: https://github.com/Kitware/trame-cookiecutter/pull/30
    description: "ci(semantic-release): fix build command"
    status: done
  - url: https://github.com/Kitware/trame-cookiecutter/pull/31
    description: "ci(precommit) pass linter and tests"
    status: done
  - url: https://github.com/Kitware/trame-cookiecutter/pull/32
    description: "docs (readme): add steps to publish a custom widget"
    status: done
  - url: https://github.com/Kitware/trame/pull/895
    description: "Add trame-radial-menu widget to the doc"
    status: done
  - url: https://github.com/Kitware/trame/pull/897
    description: "Add trame-radial-menu to the news"
    status: done
  - url: https://github.com/Kitware/trame-radial-menu/pull/1
    description: "Make open at mouse pos optional and have trame slicer example"
    status: done
  - url: https://github.com/conda-forge/staged-recipes/pull/34150
    description: "Publish to conda-forge"
    status: done
  - url: https://github.com/conda-forge/trame-radial-menu-feedstock
    description: "trame-radial-menu-feedstock repository"
    status: done
  - url: https://github.com/Kitware/trame-rca/pull/42
    description: "feat: handle two finger gestures (superseded by PR #44)"
    status: closed_unmerged
  - url: https://github.com/Kitware/trame-rca/pull/44
    description: "Gestures"
    status: done
  - url: https://github.com/Kitware/trame-rca/pull/48
    description: "Gestures (superseded by PR #49)"
    status: closed_unmerged
  - url: https://github.com/Kitware/trame-rca/pull/49
    description: "Throttle gesture events"
    status: done
  - url: https://gitlab.kitware.com/vtk/vtk/-/merge_requests/13428
    description: "Gestures"
    status: done
  - url: https://github.com/KitwareMedical/SlicerCore/pull/12
    description: "fix vtkAddon not found"
    status: open
  - url: https://github.com/Slicer/Slicer/pull/9334
    description: "Segfault overflow when one view"
    status: done

issues:
  - url: https://github.com/Kitware/trame-markdown/issues/3
    description: "Some examples are broken"
    status: done
  - url: https://github.com/Kitware/trame-vtk/issues/107
    description: "Bug with paraview >= 5.13 local rendering"
    status: open
  - url: https://github.com/Kitware/trame/issues/875
    description: "Paraview with Docker doesn't work"
    status: done
  - url: https://github.com/Kitware/trame-cookiecutter/issues/29
    description: "trame-cookiecutter doesn't publish to PyPI"
    status: done
  - url: https://gitlab.kitware.com/vtk/vtk/-/work_items/20105
    description: "endRotate event wrong mapping"
    status: done